[package]
name = "wg-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["cargo", "derive"] }
futures = "0.3.15"
ipnetwork = "0.16"
talpid-core = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-routing = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-tunnel = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-types = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-wireguard = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
thiserror = "1.0.38"
tokio = { version = "1.8", features = ["process", "rt-multi-thread", "fs"] }
tun = { version = "0.5.5", features = ["async"] }
url = "2.4"

nym-bin-common = { git = "https://github.com/nymtech/nym", tag = "nym-binaries-v2023.1-milka" }
nym-config = { git = "https://github.com/nymtech/nym", tag = "nym-binaries-v2023.1-milka" }
nym-sdk = { git = "https://github.com/nymtech/nym", tag = "nym-binaries-v2023.1-milka" }
nym-task = { git = "https://github.com/nymtech/nym", tag = "nym-binaries-v2023.1-milka" }
nym-validator-client = { git = "https://github.com/nymtech/nym", tag = "nym-binaries-v2023.1-milka" }
log = "0.4.20"
