[target.aarch64-linux-android]
rustflags = ["-L", "../../main/jniLibs/arm64-v8a"]
[target.x86_64-linux-android]
rustflags = ["-L", "../../main/jniLibs/x86_64"]
[target.armv7-linux-androideabi]
rustflags = ["-L", "../../main/jniLibs/armeabi-v7a"]
[target.i686-linux-android]
rustflags = ["-L", "../../main/jniLibs/x86"]