[target.aarch64-linux-android]
rustflags = ["-L", "./build/lib/extraJni/arm64-v8a"]
[target.x86_64-linux-android]
rustflags = ["-L", "./build/lib/extraJni/x86_64"]
[target.armv7-linux-androideabi]
rustflags = ["-L", "./build/lib/extraJni/armeabi-v7a"]
[target.i686-linux-android]
rustflags = ["-L", "./build/lib/extraJni/x86"]
