name: ci-cargo-deny
on: [pull_request]
jobs:
  cargo-deny:
    environment: BUILD
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        checks:
          # - advisories
          - licenses
          - bans sources

    continue-on-error: ${{ matrix.checks == 'licenses' }}

    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        log-level: warn
        command: check ${{ matrix.checks }}
        argument: --all-features
        credentials: https://${{ secrets.MACHINE_USER_NAME }}:${{ secrets.MACHINE_USER_PAT }}@github.com
